/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/**
 * MyEclipse Struts Creation date: 12-16-2009
 * 
 * XDoclet definition:
 * 
 * @struts.form name="addFAQForm"
 */
public class AddFAQForm extends ValidatorForm
{
	/*
	 * Generated fields
	 */

	/** answer property */
	private String answer;

	/** question property */
	private String question;

	/*
	 * Generated Methods
	 */

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request)
	{
		ActionErrors errors = new ActionErrors();

		if ((question == null) || (question.length() < 1))
			errors.add("question", new ActionError("error.question.required"));

		if ((answer == null) || (answer.length() < 1))
			errors.add("answer", new ActionError("error.answer.required"));

		return errors;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request)
	{
		// TODO Auto-generated method stub
	}

	/**
	 * Returns the answer.
	 * 
	 * @return String
	 */
	public String getAnswer()
	{
		return answer;
	}

	/**
	 * Set the answer.
	 * 
	 * @param answer
	 *            The answer to set
	 */
	public void setAnswer(String answer)
	{
		this.answer = answer;
	}

	/**
	 * Returns the question.
	 * 
	 * @return String
	 */
	public String getQuestion()
	{
		return question;
	}

	/**
	 * Set the question.
	 * 
	 * @param question
	 *            The question to set
	 */
	public void setQuestion(String question)
	{
		this.question = question;
	}
}