/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-17-2009
 * 
 * XDoclet definition:
 * @struts.form name="chooseCourseForm"
 */
public class ChooseCourseForm extends ActionForm {
/*
	private Long fee;


	private String courseinfo;


	private String description;


	private String courseid;


	private Long studentid;


	private String teacher;

	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}


	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}


	public Long getFee() {
		return fee;
	}


	public void setFee(Long fee) {
		this.fee = fee;
	}


	public String getCourseinfo() {
		return courseinfo;
	}


	public void setCourseinfo(String courseinfo) {
		this.courseinfo = courseinfo;
	}


	public String getDescription() {
		return description;
	}


	public void setDescription(String description) {
		this.description = description;
	}

	public String getCourseid() {
		return courseid;
	}

	public void setCourseid(String courseid) {
		this.courseid = courseid;
	}


	public Long getStudentid() {
		return studentid;
	}

	public void setStudentid(Long studentid) {
		this.studentid = studentid;
	}

	public String getTeacher() {
		return teacher;
	}

	public void setTeacher(String teacher) {
		this.teacher = teacher;
	}
	*/
}