/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-21-2009
 * 
 * XDoclet definition:
 * @struts.form name="faqForm"
 */
public class FaqForm extends ActionForm
{
	/*
	 * Generated fields
	 */

	/** answer property */
	private String answer;

	/** faqId property */
	private Long faqId;

	/** question property */
	private String question;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request)
	{
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request)
	{
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the answer.
	 * @return String
	 */
	public String getAnswer()
	{
		return answer;
	}

	/** 
	 * Set the answer.
	 * @param answer The answer to set
	 */
	public void setAnswer(String answer)
	{
		this.answer = answer;
	}

	/** 
	 * Returns the faqId.
	 * @return Long
	 */
	public Long getFaqId()
	{
		return faqId;
	}

	/** 
	 * Set the faqId.
	 * @param faqId The faqId to set
	 */
	public void setFaqId(Long faqId)
	{
		this.faqId = faqId;
	}

	/** 
	 * Returns the question.
	 * @return String
	 */
	public String getQuestion()
	{
		return question;
	}

	/** 
	 * Set the question.
	 * @param question The question to set
	 */
	public void setQuestion(String question)
	{
		this.question = question;
	}
}