/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-01-2010
 * 
 * XDoclet definition:
 * @struts.form name="teacherForm"
 */
public class TeacherForm extends ActionForm
{
	/*
	 * Generated fields
	 */

	/** password property */
	private String password;

	/** title property */
	private String title;

	/** description property */
	private String description;

	/** email property */
	private String email;

	/** name property */
	private String name;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request)
	{
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request)
	{
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the password.
	 * @return String
	 */
	public String getPassword()
	{
		return password;
	}

	/** 
	 * Set the password.
	 * @param password The password to set
	 */
	public void setPassword(String password)
	{
		this.password = password;
	}

	/** 
	 * Returns the title.
	 * @return String
	 */
	public String getTitle()
	{
		return title;
	}

	/** 
	 * Set the title.
	 * @param title The title to set
	 */
	public void setTitle(String title)
	{
		this.title = title;
	}

	/** 
	 * Returns the description.
	 * @return String
	 */
	public String getDescription()
	{
		return description;
	}

	/** 
	 * Set the description.
	 * @param description The description to set
	 */
	public void setDescription(String description)
	{
		this.description = description;
	}

	/** 
	 * Returns the email.
	 * @return String
	 */
	public String getEmail()
	{
		return email;
	}

	/** 
	 * Set the email.
	 * @param email The email to set
	 */
	public void setEmail(String email)
	{
		this.email = email;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName()
	{
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name)
	{
		this.name = name;
	}
}