/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package student;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dao.StudentDAO;
import dao.Student;
import student.StudentForm;

import java.util.List;
/** 
 * MyEclipse Struts
 * Creation date: 01-02-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="display" path="/student/displayInf.jsp"
 */
public class DisplayInfAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		StudentDAO stuDAO = new StudentDAO();
		Student stu;
		String stuId = "";
//		if(request.getSession().getAttribute("student") != null){
//			stuId = request.getSession().getAttribute("student").toString();
//		}
		
		//if(stuId != "")
		{
			
			List stuList = stuDAO.findByName("ice");
			if(stuList.size() > 0)
			{
				stu = (Student)stuList.get(0);
				//System.out.println(stu.getName());
				request.getSession().setAttribute("stuBean", stu);
				return mapping.findForward("display");
			}	
		}
		
		return mapping.findForward("display");
	}
//	public ActionForward displayStudent(ActionMapping mapping, ActionForm form,
//			HttpServletRequest request, HttpServletResponse response) {
//		String stuId;
//		StudentDAO stuDAO = new StudentDAO();
//		Student stu;
//		StudentForm stuForm = new StudentForm();
//		
//		if(request.getSession().getAttribute("student") != null){
//			stuId = request.getSession().getAttribute("student").toString();
//			List stuList = stuDAO.findByName(stuId);
//			if(stuList.size() > 0)
//			{
//				stu = (Student)stuList.get(0);
//				//System.out.println(stu.getName());
//				stuForm.setStudentId(stu.getStudentId());
//				stuForm.setDormitory(stu.getDormitory());
//				stuForm.setEmail(stu.getEmail());
//				stuForm.setGender(stu.getGender());
//				stuForm.setMajor(stu.getMajor());
//				stuForm.setName(stu.getName());
//				stuForm.setPhone(stu.getPhone());
//				stuForm.setPassword(stu.getPassword());
//				
//				return mapping.findForward("display");
//			}	
//		}
//		return mapping.findForward("display");
//	}
}