/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.admin;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;

import struts.form.TeacherForm;
import dao.Teacher;
import factory.HibernateSessionFactory;

/**
 * MyEclipse Struts Creation date: 01-01-2010
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/addTeacher" name="teacherForm"
 *                input="/admin/teacher.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/admin/manage.jsp"
 */
public class AddTeacherAction extends Action
{
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		TeacherForm teacherForm = (TeacherForm) form;
		Teacher t = new Teacher();
		t.setDescription(teacherForm.getDescription());
		t.setEmail(teacherForm.getEmail());
		t.setName(teacherForm.getName());
		t.setPassword(teacherForm.getPassword());
		t.setTitle(teacherForm.getTitle());

		Session session = HibernateSessionFactory.getSession();
		Transaction tx = session.beginTransaction();
		try
		{
			session.saveOrUpdate(t);

			tx.commit();
			session.close();

		} catch (HibernateException e)
		{
			e.printStackTrace();
			tx.rollback();
		}

		return mapping.findForward(util.Constants.SUCCESS);
	}
}