/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.admin;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import struts.form.admin.ManageForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-26-2009
 * 
 * XDoclet definition:
 * @struts.action path="/manage" name="manageForm" input="/admin/manage.jsp" scope="request" validate="true"
 */
public class ManageAction extends Action
{
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		ManageForm manageForm = (ManageForm) form;// TODO Auto-generated method stub
		return null;
	}
}