/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import dao.*;


import struts.form.ChooseCourseForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-17-2009
 * 
 * XDoclet definition:
 * @struts.action path="/chooseCourse" name="chooseCourseForm" input="/course/chooseCourse.jsp" scope="request" validate="true"
 * @struts.action-forward name="this" path="/course/chooseCourse.jsp" contextRelative="true"
 */
public class ChooseCourseAction extends Action {
	/*
	 * Generated Methods
	 */
	private dao.CourseDAO courseDao;
	private dao.StudentCourseDAO studentCourseDao;
	private java.util.List chooseList;

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ChooseCourseForm chooseCourseForm = (ChooseCourseForm) form;// TODO Auto-generated method stub
		if(request.getSession().getAttribute("usertype").toString().equalsIgnoreCase("student"))
		{
			Student student=(Student)(request.getSession().getAttribute("user"));
		
			chooseList=(List)(request.getSession().getAttribute("choice"));
			Course course;
			if (chooseList!=null&&chooseList.size()>0)
			{
				for(int i=0;i<chooseList.size();i++)
				{
					int j=1;
					course=(Course)(chooseList.get(i));
					studentCourseDao=new dao.StudentCourseDAO();
					StudentCourseId sd=new StudentCourseId();
					StudentCourse sc=new StudentCourse();
					sd.setCourseId(course.getCourseId());
					sd.setStudentId(student.getStudentId());
					sc.setId(sd);
					studentCourseDao.save(sc);
					System.out.print("ok");
					
					
				}
			return mapping.findForward("succeed");
			}
			else
			{
				System.out.println("chooselist is null");
			}
		}
		return mapping.findForward("fail");	
	}
		
		
		
	}
