/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import struts.form.LoginForm;

/**
 * MyEclipse Struts Creation date: 01-03-2010
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/logout" name="loginForm" scope="request"
 *                validate="true"
 * @struts.action-forward name="success" path="/login.jsp" redirect="true"
 */
public class LogoutAction extends Action
{
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		LoginForm loginForm = (LoginForm) form;

		request.getSession().invalidate();
		System.out.println("Log out.");
		return mapping.findForward(util.Constants.SUCCESS);
	}
}