/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import test.struts.form.TestForm;
import dao.Test;
import dao.TestDAO;

/**
 * MyEclipse Struts Creation date: 12-12-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/test" name="testForm" input="/test/test.jsp"
 *                scope="request" validate="true"
 */
public class TestAction extends Action
{
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		TestForm testForm = (TestForm) form;// TODO Auto-generated method stub
		ActionForward forward = new ActionForward();

		String name = testForm.getName();
		String password = testForm.getPassword();

		Test test = new Test();
		test.setName(name);
		test.setPassword(password);

		TestDAO testDAO = new TestDAO();
		testDAO.save(test);

		if (name.equalsIgnoreCase("test"))
			forward = mapping.findForward("testSuccess");
		else
			forward = mapping.findForward("testFailure");
		return forward;
	}
}